CREATE TABLE book (
id INT NOT NULL AUTO_INCREMENT,
isbn VARCHAR(50) NULL, 
page INT NOT NULL,
author VARCHAR(20) NOT NULL,
kind VARCHAR(10) NOT NULL,
location VARCHAR(10) NOT NULL,
PRIMARY KEY(id));


