# Generated by Django 2.2 on 2024-06-26 02:27

from django.db import migrations


def save_email_domain(apps, schema_editor):
    User = apps.get_model('coplate', 'User')
    for user in User.objects.all():
        user.email_domain = user.email.split('@')[1]
        user.save()
class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0006_user_email_domain'),
    ]

    operations = [
        migrations.RunPython(save_email_domain, migrations.RunPython.noop),
    ]
