# Generated by Django 2.2 on 2024-06-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0010_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commnet',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dt_created']},
        ),
    ]
