# Generated by Django 4.2.13 on 2024-06-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dt_created']},
        ),
    ]
