# Generated by Django 2.2 on 2024-05-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descriptio',
            new_name='description',
        ),
    ]
